#!/bin/bash

# ------------------------------------
# Custom aliases
# ------------------------------------

declare -a chromes=('chromium-browser' 'chromium' 'google-chrome')
for chrome in "${chromes[@]}" ; do
    if which $chrome >/dev/null; then
        alias chrome=$chrome
        break
    fi
done

libre_office() {
    libreoffice "$@" &> /dev/null &
}
alias lo=libre_office

xdg_open() {
    xdg-open "$@" &> /dev/null &
}
alias obri=xdg_open
alias pytest='python3 -m pytest'

alias autosource="source $HOME/.bashrc"
alias usr="cd $USR"

alias clip="xclip -sel clipboard"
