#!/bin/bash

# ------------------------------------
# Custom aliases
# ------------------------------------

# alias chrome='google-chrome'
if which chromium-browser >/dev/null; then
    alias chrome='chromium-browser'
elif which chromium >/dev/null; then
    alias chrome='chromium'
fi

libre_office() {
    libreoffice "$@" &> /dev/null &
}
alias lo=libre_office

xdg_open() {
    xdg-open "$@" &> /dev/null &
}
alias obri=xdg_open
alias pytest='python3 -m pytest'

alias autosource="source $HOME/.bashrc"
alias usr="cd ~/usr"

alias nvim="nvim -u ~/usr/etc/nvim/init.vim"
alias vi="nvim"

alias clip="xclip -sel clipboard"
