#!/bin/bash

# ------------------------------------
# Custom aliases
# ------------------------------------

if ! which chrome &>/dev/null; then
    declare -a chromes=('chromium-browser' 'chromium' 'google-chrome')
    for chrome in "${chromes[@]}" ; do
        if which $chrome &>/dev/null; then
            alias chrome=$chrome
            break
        fi
    done
fi

libre_office() {
    libreoffice "$@" &> /dev/null &
}
alias lo=libre_office

xdg_open() {
    xdg-open "$@" &> /dev/null &
}

if which xdg_open &>/dev/null; then
    alias obri=xdg_open
elif which explorer.exe &>/dev/null; then
    alias obri=explorer.exe
fi

alias pytest='python3 -m pytest'

alias autosource="source $HOME/.bashrc"
alias usr="cd $USR"

alias clip="xclip -sel clipboard"
