# Custom bash configuration
# @author joapuiib

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

if [ -d "$HOME/usr/bin" ] ; then
    PATH="$HOME/usr/bin:$PATH"
fi

USR="$HOME/usr"
# Source autocompletion scripts for user scripts
if [ -d $USR/etc/bash_completion ]; then
    for f in $USR/etc/bash_completion/*; do
        source $f
    done
fi

# Prompt
source git-prompt.sh
export PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[33m\]$(__git_ps1) \[\033[00m\]$ '

# Source aliases
source $USR/bashrc/complete_alias
source $USR/bashrc/dockerrc
source $USR/bashrc/aliases
source $USR/bashrc/docencia
source $USR/bashrc/gitrc

# Bin folders
if [ -d $HOME/docencia/bin ] ; then
    PATH="$HOME/docencia/bin:$PATH"
    if [ -d $HOME/docencia/python/git_tools ] ; then
        PATH="$HOME/docencia/python/git_tools:$PATH"
    fi
fi
if [ -d $HOME/docencia/bin ] ; then
    PATH="$HOME/peticio_fct/bin:$PATH"
fi

# LANG
LANG="en_US.utf-8"
export LANG

# Set vim default editor
if which nvim &>/dev/null ; then
    export MYVIMRC="~/usr/etc/nvim/init.vim"
    export VIMINIT="source $MYVIMRC"
    export nvim="$HOME/usr/etc/nvim"
    alias vi="nvim"
    alias cdnvim="cd $nvim"
fi
export VISUAL=nvim
export EDITOR="$VISUAL"

# Git config file
# export GIT_CONFIG=$USR/bashrc/gitconfig

# ?
# stty -ixon

### RUBY CONFIG
# Install Ruby Gems to ~/gems' >> ~/.bashrc
# export GEM_HOME="$HOME/.gems"
export PATH="$HOME/.gems/bin:$PATH"
export PATH="$HOME/.rbenv/bin:$PATH"
which rbenv &>/dev/null
if [ $? == 0 ] ; then
    eval "$(rbenv init -)"
fi

### Node modules
export NODE_PATH=/usr/local/lib/node_modules/

# Prompt command
# Comanda que s'executara sempre que el Bash mostre el prompt
if which augment_path.sh &>/dev/null ; then
    export PATH_DEFAULT="$PATH"
    # PROMPT_COMMAND="source augment_path.sh"
fi

# Shared Lib path
export LD_LIBRARY_PATH="/usr/local/lib"

# Cuda
export PATH="$PATH:/usr/local/cuda/bin"

# NVM
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
