#!/bin/bash

# Declara una variable d'entorn i un alias per anar a la ruta
# $1 id alias/variable
# $2 ruta
_set_variable_alias () {
    # -g declares a global variable
    declare -g -x "$1"="$2"
    alias "$1"="cd $2"
}

dovers="$HOME/docencia/python/dovers"

if [ -d "$HOME/docencia/middleman/fp/" ] ; then
    _set_variable_alias "fp" "$HOME/docencia/middleman/fp/"
elif [ -d "$HOME/fp/" ] ; then
    _set_variable_alias "fp" "$HOME/fp/"
else
    return
fi

_set_variable_alias "fpd" "$fp/data/"
_set_variable_alias "fps" "$fp/source/"
_set_variable_alias "fpt" "$fp/source/templates/"
_set_variable_alias "fpl" "$fp/source/layouts/"
_set_variable_alias "fpc" "$fp/source/stylesheets/"
_set_variable_alias "fpj" "$fp/source/javascripts/"

fpr () {
    cd $fp
    ./run.sh $@
}

declare -A moduls
moduls=()
moduls+=(["m1"]="DAM-M01")
moduls+=(["m3"]="DAM-M03")
moduls+=(["m16"]="DAM-M16")
moduls+=(["llmq"]="ASIX-LLMQ")
moduls+=(["bd"]="DAM-BD")
moduls+=(["dba"]="DAM-BD")
moduls+=(["dbms"]="ASIX-SGBD")
moduls+=(["batx"]="BATX-TIC1")
moduls+=(["cefire"]="CEFIRE")
moduls+=(["ed"]="DAM-ED")
moduls+=(["psp"]="DAM-PSP")
moduls+=(["si"]="SMX-SI")
moduls+=(["tut"]="DAW-TUT")

declare -A abbrvs
abbrvs=()
abbrvs+=(["f"]="files")
abbrvs+=(["m"]="materials")
abbrvs+=(["s"]="slides")
abbrvs+=(["e"]="exercicis")
abbrvs+=(["p"]="practiques")
abbrvs+=(["p"]="practices")
abbrvs+=(["x"]="exams")

for modul in ${!moduls[@]}; do
    codi=${moduls[$modul]}
    _set_variable_alias "${modul}" "$fps/$codi"
    if [ -d "$fps/$codi/files" ]; then
        _set_variable_alias "${modul}f" "$fps/$codi/files"
    fi
    _set_variable_alias "${modul}d" "$fpd/moduls/$codi"
    if [ -d $fps/$codi ]; then
        UDS=`find "$fps/$codi" -maxdepth 1 -name UD\* | sed 's/^.*UD//'`
        for i in $UDS; do
            _set_variable_alias "${modul}$i" "$fps/$codi/UD$i"
            for abbrv in ${!abbrvs[@]}; do
                folder=${abbrvs[$abbrv]}
                if [ -d "$fps/$codi/UD$i/$folder" ]; then
                    _set_variable_alias "${modul}${i}${abbrv}" "$fps/$codi/UD${i}/${folder}"
                fi
            done
        done
    fi
done
unset codi

GREEN='\033[0;32m'
RED='\033[0;31m'
RESET='\033[0m'

alias td="vi $HOME/docencia/TODO.txt"
_push_todo(){
    echo -e "${GREEN}git -C $HOME/docencia pull${RESET}"
    git -C $HOME/docencia pull
    echo -e "${GREEN}git -C $HOME/docencia add TODO.txt${RESET}"
    git -C $HOME/docencia add TODO.txt
    echo -e "${GREEN}git -C $HOME/docencia commit -m "Update TODO"${RESET}"
    git -C $HOME/docencia commit -m "Update TODO"
    echo -e "${GREEN}git -C $HOME/docencia push${RESET}"
    git -C $HOME/docencia push
}
alias tdp=_push_todo
