#!/bin/bash

# Declara una variable d'entorn i un alias per anar a la ruta
# $1 id alias/variable
# $2 ruta
_set_variable_alias () {
    # -g declares a global variable
    declare -g -x "$1"="$2"
    alias "$1"="cd $2"
}

dovers="$HOME/docencia/python/dovers"

if [ -d "$HOME/docencia/middleman/itb/" ] ; then
    _set_variable_alias "itb" "$HOME/docencia/middleman/itb/"
elif [ -d "$HOME/itb/" ] ; then
    _set_variable_alias "itb" "$HOME/itb/"
else
    return
fi

_set_variable_alias "itbd" "$itb/data/"
_set_variable_alias "itbs" "$itb/source/"
_set_variable_alias "itbt" "$itb/source/templates/"
_set_variable_alias "itbl" "$itb/source/layouts/"
_set_variable_alias "itbc" "$itb/source/stylesheets/"
_set_variable_alias "itbj" "$itb/source/javascripts/"

itbrun () {
    cd $itb
    ./run.sh $@
}

declare -A moduls
moduls=()
moduls+=(["itb_m1"]="DAM-M01")
moduls+=(["itb_m3"]="DAM-M03")
moduls+=(["itb_m16"]="DAM-M16")
moduls+=(["itb_llmq"]="ASIX-LLMQ")
moduls+=(["itb_bd"]="DAM-BD")
moduls+=(["itb_dba"]="DAM-BD")
moduls+=(["itb_dbms"]="ASIX-SGBD")
moduls+=(["itb_batx"]="BATX-TIC1")
moduls+=(["itb_cefire"]="CEFIRE")
moduls+=(["itb_ed"]="DAM-ED")
moduls+=(["itb_psp"]="DAM-PSP")
moduls+=(["itb_si"]="SMX-SI")
moduls+=(["itb_tut"]="DAW-TUT")

declare -A abbrvs
abbrvs=()
abbrvs+=(["c"]="components")
abbrvs+=(["f"]="files")
abbrvs+=(["m"]="materials")
abbrvs+=(["s"]="slides")
abbrvs+=(["e"]="exercicis")
abbrvs+=(["p"]="practiques")
abbrvs+=(["p"]="practices")
abbrvs+=(["x"]="exams")

for modul in ${!moduls[@]}; do
    codi=${moduls[$modul]}
    _set_variable_alias "${modul}" "$itbs/$codi"
    if [ -d "$itbs/$codi/files" ]; then
        _set_variable_alias "${modul}f" "$itbs/$codi/files"
    fi
    if [ -d "$itbs/$codi/components" ]; then
        _set_variable_alias "${modul}c" "$itbs/$codi/components"
    fi
    _set_variable_alias "${modul}d" "$itbd/moduls/$codi"
    if [ -d $itbs/$codi ]; then
        UDS=`find "$itbs/$codi" -maxdepth 1 -name UD\* | sed 's/^.*UD//'`
        for i in $UDS; do
            _set_variable_alias "${modul}$i" "$itbs/$codi/UD$i"
            for abbrv in ${!abbrvs[@]}; do
                folder=${abbrvs[$abbrv]}
                if [ -d "$itbs/$codi/UD$i/$folder" ]; then
                    _set_variable_alias "${modul}${i}${abbrv}" "$itbs/$codi/UD${i}/${folder}"
                fi
            done
        done
    fi
done
unset codi

for bd in "institut" "ciclisme" "musica" "cinema"; do
    _set_variable_alias "bdf_$bd" "$bdf/ca/$bd"
    _set_variable_alias "bdc_$bd" "$bdc/ca/$bd"
done

GREEN='\033[0;32m'
RED='\033[0;31m'
RESET='\033[0m'

#### MKDOCS
if [ -d "$HOME/mkdocs" ]; then
    alias td="find $HOME/mkdocs -name \*.md -exec grep @TODO {} /dev/null \;"
fi

declare -A mkdocs_folders
mkdocs_folders=()
mkdocs_folders+=(["curs-git"]="cursgit")
mkdocs_folders+=(["smx-si"]="si")
mkdocs_folders+=(["daw-ed"]="ed")
mkdocs_folders+=(["bd"]="bd")
mkdocs_folders+=(["dam-psp"]="psp")
mkdocs_folders+=(["iabd-saa"]="saa")

for folder in ${!mkdocs_folders[@]}; do
    codi=${mkdocs_folders[$folder]}

    if [ -d "$HOME/mkdocs/$folder" ]; then
        _set_variable_alias "${codi}" "$HOME/mkdocs/$folder"
        if [ -d "$HOME/mkdocs/$folder/docs" ]; then
            _set_variable_alias "${codi}d" "$HOME/mkdocs/$folder/docs"
        fi
        if [ -d "$HOME/mkdocs/$folder/docs/files" ]; then
            _set_variable_alias "${codi}f" "$HOME/mkdocs/$folder/docs/files"
        fi

        if [ -d "$HOME/mkdocs/$folder/docs/apunts" ]; then
            _set_variable_alias "${codi}a" "$HOME/mkdocs/$folder/docs/apunts"

            basedir="$HOME/mkdocs/$folder/docs/apunts"
            # Find directories starting with a number
            for dir in $(find $basedir -mindepth 1 -maxdepth 1 -type d); do
              relative_dir=${dir#$basedir/}

              # Extract the leading number using parameter expansion
              number=$(basename "$relative_dir" | grep -o '^[0-9]*')
              if [ -n "$number" ]; then
                  number=$((10#$number))  # Convert to decimal
                  _set_variable_alias "${codi}${number}" "$HOME/mkdocs/$folder/docs/apunts/$relative_dir"
              fi
            done
        fi
    fi
done
unset codi, folder, mkdocs_folders
