#!/bin/bash

# Declara una variable d'entorn i un alias per anar a la ruta
# $1 id alias/variable
# $2 ruta
set_variable_alias () {
    # -g declares a global variable
    declare -g -x "$1"="$2"
    alias "$1"="cd $2"
}


dovers="$HOME/docencia/python/dovers"

if [ -d "$HOME/docencia/middleman/itb/" ] ; then
    set_variable_alias "itb" "$HOME/docencia/middleman/itb/"
elif [ -d "$HOME/itb/" ] ; then
    set_variable_alias "itb" "$HOME/itb/"
else
    return
fi

declare -A repos
repos=()
repos+=(["itb"]="$itb")

set_variable_alias "itb_data" "$itb/data"
set_variable_alias "itb_source" "$itb/source"
set_variable_alias "itb_templates" "$itb/templates"

declare -A moduls
moduls=()
moduls+=(["m1"]="DAM-M01")
moduls+=(["m3"]="DAM-M03")
moduls+=(["m16"]="DAM-M16")
moduls+=(["llmq"]="ASIX-LLMQ")
moduls+=(["bbdd"]="DAW-BBDD")
moduls+=(["dbms"]="ASIX-SGBD")

for modul in ${!moduls[@]}; do
    codi=${moduls[$modul]}
    set_variable_alias "${modul}"      "$itb_source/$codi"
    set_variable_alias "${modul}_data" "$itb_data/moduls/$codi"
    if [ -d $itb_source/$codi ]; then
        UFS=`find "$itb_source/$codi" -maxdepth 1 -name UF\* | sed 's/^.*UF//'`
        for i in $UFS; do
            set_variable_alias "${modul}$i" "$itb_source/$codi/UF$i"
        done
    fi
done
unset codi

GREEN='\033[0;32m'
RED='\033[0;31m'
RESET='\033[0m'
repos+=(["docencia"]="$HOME/docencia")
repos+=(["grade"]="$HOME/docencia/grade")
repos+=(["jutge"]="$HOME/docencia/python/jutge")
repos+=(["gripau"]="$HOME/docencia/gripau/gripau-server")

for repo in ${!repos[@]}; do
    repo_path=${repos[$repo]}
    alias "$repo"="cd $repo_path"
done

alias todo="vi $HOME/docencia/TODO.txt"

check_repo() {
    if git -C $2 diff --quiet ; then
        echo -e "$1($2): ${GREEN}clean${RESET}"
    else
        echo -e "$1($2): ${RED}dirty${RESET}"
    fi
}

check_status() {
    for repo in ${!repos[@]}; do
        repo_path=${repos[$repo]}
        check_repo $repo $repo_path
    done
}

alias status=check_status

