#!/bin/bash 

# ------------------------------------
# Git alias and function
# ------------------------------------

alias gs="git status"
complete -F _complete_alias gs

alias gp="git push"
complete -F _complete_alias gp

alias gpl="git pull"
complete -F _complete_alias gpl

alias ga="git add"
complete -F _complete_alias ga

alias gc="git commit"
complete -F _complete_alias gc

alias gd="git diff"
complete -F _complete_alias gd

alias gch="git checkout"
complete -F _complete_alias gch

alias gsw="git show"
complete -F _complete_alias gsw

alias gl="git lg"
complete -F _complete_alias gl

gla() {
    ARGS="$@"
    if git cat-file -t origin/gh-pages &>/dev/null
    then
        ARGS="$ARGS --not origin/gh-pages"
    fi
    git lg $ARGS --all
}

# Show all alias related docker
galias() { alias | grep 'git' | sed "s/^\([^=]*\)=\(.*\)/\1 => \2/"| sed "s/['|\']//g" | sort; }

declare -A repos
repos=()

GREEN='\033[0;32m'
RED='\033[0;31m'
RESET='\033[0m'

repos+=(["itb"]="$itb")
repos+=(["docencia"]="$HOME/docencia")
repos+=(["grade"]="$HOME/docencia/grade")
repos+=(["jutge"]="$HOME/docencia/python/jutge")
repos+=(["gripau"]="$HOME/docencia/gripau/gripau-server")
repos+=(["usr"]="$HOME/usr")

for repo in ${!repos[@]}; do
    repo_path=${repos[$repo]}
    alias "$repo"="cd $repo_path"
done

_check_repository() {
    if [ -d "$2" ]; then
        if git -C $2 diff --quiet ; then
            echo -e "$1 ($2): ${GREEN}clean${RESET}"
        else
            echo -e "$1 ($2): ${RED}dirty${RESET}"
        fi
    else
        echo -e "$1 ($2): ${RED}not found${RESET}"
    fi
}

_check_status() {
    for repo in ${!repos[@]}; do
        repo_path=${repos[$repo]}
        _check_repository $repo $repo_path
    done
}

_pull_repository() {
    if [ -d "$2" ]; then
        echo -e "${GREEN}pulling $1: ($2) ${RESET}"
        # git -C $2 checkout master
        git -C $2 pull -f --tags --all
    else 
        echo -e "$1 ($2): ${RED}not found${RESET}"
    fi
}
_pull_repositories() {
    for repo in ${!repos[@]}; do
        repo_path=${repos[$repo]}
        _pull_repository $repo $repo_path
    done
}

alias status=_check_status
alias pull=_pull_repositories
